name: Autograding Tests
'on':
- push
permissions:
  checks: write
  actions: read
  contents: read
env:
  MAVEN_ARGS: >-
    -B
    -ntp
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'
    - name: Resolve Project Maven Dependencies
      run: test -f pom.xml && mvn -B -ntp dependency:go-offline dependency:resolve-plugins || true

    - name: "Rubric: Check coding standard"
      id: checkstyle
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Rubric: Check coding standard"
        command: mvn -B -ntp checkstyle:check
        timeout: 10
        max-score: 10
        
    - name: "Rubric: Save Customer Test"
      id: savecustomertest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Rubric: Save Customer Test"
        command: mvn -B -ntp -Dtest=CustomerRepositoryTest#testSaveCustomer test
        timeout: 10
        max-score: 10
      
    - name: "Rubric: Find Customer by Name Test"
      id: findcustomerbyname
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Rubric: Find Customer by Name Test"
        command: mvn  -Dtest=CustomerRepositoryTest#testFindByName test
        timeout: 10
        max-score: 10
    
    - name: "Rubric: Find Customer by Email Test"
      id: findcustomerbyemail
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Rubric: Find Customer by Email Test"
        command: mvn  -Dtest=CustomerRepositoryTest#testFindByEmail test
        timeout: 10
        max-score: 10
    
    - name: "Rubric: Save Order Test"
      id: saveordertest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Rubric: Save Order Test"
        command: mvn -Dtest=OrderRepositoryTest#testSaveOrder test
        timeout: 10
        max-score: 10
    
    - name: "Rubric: Find Orders by Status Test"
      id: findordersbystatus
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Rubric: Find Orders by Status Test"
        command: mvn  -Dtest=OrderRepositoryTest#testFindByStatus test
        timeout: 10
        max-score: 10
    
    - name: "Rubric: Find Orders by Date Range Test"
      id: findordersbydaterange
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Rubric: Find Orders by Date Range Test"
        command: mvn -Dtest=OrderRepositoryTest#testFindByOrderDateBetween test
        timeout: 10
        max-score: 10
    
    - name: "Rubric: Save Product Test"
      id: saveproducttest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Rubric: Save Product Test"
        command: mvn  -Dtest=ProductRepositoryTest#testSaveProduct test
        timeout: 10
        max-score: 10
    
    - name: "Rubric: Find Product by Name Test"
      id: findproductbyname
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Rubric: Find Product by Name Test"
        command: mvn -Dtest=ProductRepositoryTest#testFindByName test
        timeout: 10
        max-score: 10
    
    - name: "Rubric: Find Products by Price Less Than Test"
      id: findproductsbypricelessthan
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Rubric: Find Products by Price Less Than Test"
        command: mvn  -Dtest=ProductRepositoryTest#testFindByPriceLessThan test
        timeout: 10
        max-score: 10
      

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SAVE_CUSTOMER_TEST_RESULTS: "${{steps.savecustomertest.outputs.result}}"
        FIND_CUSTOMER_BY_NAME_RESULTS: "${{steps.findcustomerbyname.outputs.result}}"
        FIND_CUSTOMER_BY_EMAIL_RESULTS: "${{steps.findcustomerbyemail.outputs.result}}"
        SAVE_ORDER_TEST_RESULTS: "${{steps.saveordertest.outputs.result}}"
        FIND_ORDERS_BY_STATUS_RESULTS: "${{steps.findordersbystatus.outputs.result}}"
        FIND_ORDERS_BY_DATE_RANGE_RESULTS: "${{steps.findordersbydaterange.outputs.result}}"
        SAVE_PRODUCT_TEST_RESULTS: "${{steps.saveproducttest.outputs.result}}"
        FIND_PRODUCT_BY_NAME_RESULTS: "${{steps.findproductbyname.outputs.result}}"
        FIND_PRODUCTS_BY_PRICE_LESS_THAN_RESULTS: "${{steps.findproductsbypricelessthan.outputs.result}}"
        CHECKSTYLE_RESULTS: "${{steps.checkstyle.outputs.result}}"
      with:
        runners:  checkstyle,savecustomertest,findcustomerbyname,findcustomerbyemail,saveordertest,findordersbystatus,findordersbydaterange,saveproducttest,findproductbyname,findproductsbypricelessthan
          
