name: Autograding Tests
'on':
- push
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'
    - name: Resolve Autograder Maven Dependencies
      run: mvn -f .autograde/pom.xml dependency:go-offline dependency:resolve-plugins
    - name: Resolve Project Maven Dependencies
      run: test -f pom.xml && mvn dependency:go-offline dependency:resolve-plugins || true

    - name: "Rubric: Check coding standard"
      id: checkstyle
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Rubric: Check coding standard"
        command: mvn checkstyle:check
        timeout: 10
        max-score: 10
        
    - name: "Rubric: Save Customer Test"
      id: save-customer-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Rubric: Save Customer Test"
        command: mvn -f .autograde/pom.xml -Dtest=CustomerRepositoryTest#testSaveCustomer test
        timeout: 10
        max-score: 10
      
    - name: "Rubric: Find Customer by Name Test"
      id: find-customer-by-name
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Rubric: Find Customer by Name Test"
        command: mvn -f .autograde/pom.xml -Dtest=CustomerRepositoryTest#testFindByName test
        timeout: 10
        max-score: 10
    
    - name: "Rubric: Find Customer by Email Test"
      id: find-customer-by-email
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Rubric: Find Customer by Email Test"
        command: mvn -f .autograde/pom.xml -Dtest=CustomerRepositoryTest#testFindByEmail test
        timeout: 10
        max-score: 10
    
    - name: "Rubric: Save Order Test"
      id: save-order-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Rubric: Save Order Test"
        command: mvn -f .autograde/pom.xml -Dtest=OrderRepositoryTest#testSaveOrder test
        timeout: 10
        max-score: 10
    
    - name: "Rubric: Find Orders by Status Test"
      id: find-orders-by-status
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Rubric: Find Orders by Status Test"
        command: mvn -f .autograde/pom.xml -Dtest=OrderRepositoryTest#testFindByStatus test
        timeout: 10
        max-score: 10
    
    - name: "Rubric: Find Orders by Date Range Test"
      id: find-orders-by-date-range
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Rubric: Find Orders by Date Range Test"
        command: mvn -f .autograde/pom.xml -Dtest=OrderRepositoryTest#testFindByOrderDateBetween test
        timeout: 10
        max-score: 10
    
    - name: "Rubric: Save Product Test"
      id: save-product-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Rubric: Save Product Test"
        command: mvn -f .autograde/pom.xml -Dtest=ProductRepositoryTest#testSaveProduct test
        timeout: 10
        max-score: 10
    
    - name: "Rubric: Find Product by Name Test"
      id: find-product-by-name
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Rubric: Find Product by Name Test"
        command: mvn -f .autograde/pom.xml -Dtest=ProductRepositoryTest#testFindByName test
        timeout: 10
        max-score: 10
    
    - name: "Rubric: Find Products by Price Less Than Test"
      id: find-products-by-price-less-than
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Rubric: Find Products by Price Less Than Test"
        command: mvn -f .autograde/pom.xml -Dtest=ProductRepositoryTest#testFindByPriceLessThan test
        timeout: 10
        max-score: 10
      

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SAVE_CUSTOMER_TEST_RESULTS: "${{steps.save-customer-test.outputs.result}}"
        FIND_CUSTOMER_BY_NAME_RESULTS: "${{steps.find-customer-by-name.outputs.result}}"
        FIND_CUSTOMER_BY_EMAIL_RESULTS: "${{steps.find-customer-by-email.outputs.result}}"
        SAVE_ORDER_TEST_RESULTS: "${{steps.save-order-test.outputs.result}}"
        FIND_ORDERS_BY_STATUS_RESULTS: "${{steps.find-orders-by-status.outputs.result}}"
        FIND_ORDERS_BY_DATE_RANGE_RESULTS: "${{steps.find-orders-by-date-range.outputs.result}}"
        SAVE_PRODUCT_TEST_RESULTS: "${{steps.save-product-test.outputs.result}}"
        FIND_PRODUCT_BY_NAME_RESULTS: "${{steps.find-product-by-name.outputs.result}}"
        FIND_PRODUCTS_BY_PRICE_LESS_THAN_RESULTS: "${{steps.find-products-by-price-less-than.outputs.result}}"
        CHECKSTYLE_RESULTS: "${{steps.checkstyle.outputs.result}}"
      with:
        runners: >-
          checkstyle,
          save-customer-test,
          find-customer-by-name,
          find-customer-by-email,
          save-order-test,
          find-orders-by-status,
          find-orders-by-date-range,
          save-product-test,
          find-product-by-name,
          find-products-by-price-less-than
          
